env:
  - LD_LIBRARY_PATH=/usr/local/lib
notifications:
  email:
    - letang.jeremy@gmail.com
before_install:
  - yes | sudo add-apt-repository ppa:cmrx64/cargo
  - sudo apt-get update
install:
  - curl http://static.rust-lang.org/rustup.sh | sudo sh -
  - sudo apt-get install libportaudio-dev
  - sudo apt-get install cargo
env:
  - RUST_TEST_TASKS=1
script:
  - cargo build
