env:
    - LD_LIBRARY_PATH=/usr/local/lib
language: rust
rust:
    - nightly
    - 1.0.0-beta
os:
    - linux
    - osx
notifications:
  email:
    - letang.jeremy@gmail.com
    - mitchell.nordine@gmail.com
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install libportaudio-dev
script:
    - cargo build --verbose
    - cargo test --verbose
