[package]

name = "portaudio"
version = "0.4.6"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>",
           "Mitchell Nordine <mitchell.nordine@gmail.com>"]
description = "PortAudio bindings for Rust."
license = "MIT"
build = "build.rs"
homepage = "https://github.com/jeremyletang/rust-portaudio"
repository = "https://github.com/jeremyletang/rust-portaudio.git"

[lib]

name = "portaudio"
crate-type = ["dylib", "rlib"]

[build-dependencies]
pkg-config = "*"

[dependencies]
bitflags = "*"
libc = "*"
num = "*"
