[package]

name = "portaudio"
version = "0.3.4"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>"]
description = "Portaudio binding for Rust"
license = "MIT"
build = "build.rs"
homepage = "https://github.com/jeremyletang/rust-portaudio"
repository = "https://github.com/jeremyletang/rust-portaudio.git"

[lib]

name = "portaudio"
crate-type = ["dylib", "rlib"]

[build-dependencies]
pkg-config = "*"
