[package]

name = "rust-portaudio"
version = "0.3.0"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>"]
description = "Portaudio binding for Rust"
license = "MIT"

[lib]

name = "portaudio"
crate-type = ["dylib", "rlib"]
