[package]

name = "portaudio"
version = "0.6.1"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>",
           "Mitchell Nordine <mitchell.nordine@gmail.com>"]
description = "PortAudio bindings for Rust."
license = "MIT"
build = "build.rs"
homepage = "https://github.com/jeremyletang/rust-portaudio"
repository = "https://github.com/jeremyletang/rust-portaudio.git"

[lib]
name = "portaudio"
crate-type = ["rlib"]

[build-dependencies]
pkg-config = "0.3.6"

[dependencies]
bitflags = "0.3.3"
libc = "0.2.4"
num = { version = "0.1.29", default-features = false }
